server:
  port: 8081
  servlet:
    context-path: /comedy-club
  compression:
    enabled: true
    mimeTypes: application/json
spring:
  application:
    name: comedy-club
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:26257/defaultdb
    username: admin
    password: admin

management:
  endpoint:
    health:
      probes:
        enabled: true