server:
  port: 8080
  servlet:
    context-path: /comedy-club
  compression:
    enabled: true
    mimeTypes: application/json
spring:
  application:
    name: comedy-club
management:
  endpoint:
    health:
      probes:
        enabled: true